"""
agent.py – Entry-point for the MCP AI agent.

Execution flow:
  1. Parse CLI arguments (prompt, target-repo, branch).
  2. Load the system prompt from ``prompts/system_prompt.md``.
  3. Build the tool inventory and pass it to the LLM.
  4. Iterate: ask the LLM which tool to use next → execute it → repeat.
  5. Once the LLM signals completion, write all generated files to the
     target repository via ``repo_manager``.

The agent is deliberately LLM-provider agnostic.  The default backend uses
the OpenAI Chat Completions API, but any provider that speaks the same JSON
schema can be substituted by changing ``_call_llm()``.
"""

from __future__ import annotations

import argparse
import json
import logging
import os
import pathlib
import sys

# Ensure the project root is on the path when running as a script
PROJECT_ROOT = str(pathlib.Path(__file__).resolve().parent.parent)
if PROJECT_ROOT not in sys.path:
    sys.path.insert(0, PROJECT_ROOT)

from agent import config
from agent import repo_manager
from agent import tool_router

logger = logging.getLogger(__name__)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s  %(levelname)-8s  %(name)s – %(message)s",
)


# ---------------------------------------------------------------------------
# LLM integration
# ---------------------------------------------------------------------------

def _load_system_prompt() -> str:
    """Read the system prompt from ``prompts/system_prompt.md``."""
    prompt_path = pathlib.Path(PROJECT_ROOT) / "prompts" / "system_prompt.md"
    if prompt_path.exists():
        return prompt_path.read_text(encoding="utf-8")
    return "You are an AI coding agent. Use the available tools to complete the user's request."


def _build_tool_descriptions() -> str:
    """Format the registered tools as a numbered list for inclusion in the prompt."""
    tools = tool_router.list_tools()
    lines = ["Available MCP tools:"]
    for i, t in enumerate(tools, 1):
        lines.append(f"  {i}. {t['name']:20s} – {t['description']}")
    return "\n".join(lines)


def _call_llm(messages: list[dict]) -> str:
    """
    Send *messages* to the configured LLM and return the assistant reply.

    Requires ``OPENAI_API_KEY`` to be set.  Falls back to a stub response
    when no key is available so the agent can be exercised without credentials.
    """
    if not config.OPENAI_API_KEY:
        logger.warning(
            "OPENAI_API_KEY is not set.  Using stub LLM response for testing."
        )
        # Stub: instruct the agent to generate a hello-world file and finish.
        return json.dumps({
            "action": "write_file",
            "path": "generated/hello.py",
            "content": '"""Auto-generated by MCP AI Bot."""\n\nprint("Hello from MCP!")\n',
            "done": True,
        })

    try:
        import openai  # type: ignore
    except ImportError as exc:
        raise RuntimeError(
            "openai package is not installed.  Add it to requirements.txt."
        ) from exc

    client = openai.OpenAI(api_key=config.OPENAI_API_KEY)
    response = client.chat.completions.create(
        model=config.OPENAI_MODEL,
        messages=messages,
        max_tokens=config.OPENAI_MAX_TOKENS,
        response_format={"type": "json_object"},
    )
    return response.choices[0].message.content or ""


# ---------------------------------------------------------------------------
# Agent loop
# ---------------------------------------------------------------------------

def _parse_action(llm_reply: str) -> dict:
    """Parse the LLM's JSON reply into an action dict."""
    try:
        return json.loads(llm_reply)
    except json.JSONDecodeError:
        logger.error("LLM returned non-JSON reply: %s", llm_reply)
        return {"action": "noop", "done": True}


def run_agent(prompt: str, target_repo: str, branch: str) -> None:
    """
    Run the agent loop for the given *prompt*.

    Parameters
    ----------
    prompt:
        The user's natural-language task description.
    target_repo:
        Target GitHub repository (``owner/name``) where generated files will
        be committed.
    branch:
        Branch in *target_repo* to push changes to.
    """
    logger.info("Starting MCP agent | repo=%s branch=%s", target_repo, branch)

    # Clone the target repository
    clone_path = repo_manager.clone(target_repo, branch)

    system_prompt = _load_system_prompt()
    tool_descriptions = _build_tool_descriptions()

    # Initial message list
    messages: list[dict] = [
        {
            "role": "system",
            "content": (
                f"{system_prompt}\n\n"
                f"{tool_descriptions}\n\n"
                "Respond ONLY with a JSON object.  Each response must include:\n"
                "  - 'action': one of 'use_tool' | 'write_file' | 'noop'\n"
                "  - 'done': true when the task is complete, false otherwise\n"
                "\nFor 'use_tool': include 'tool' (tool name) and 'params' (dict).\n"
                "For 'write_file': include 'path' (relative to repo root) and 'content'.\n"
            ),
        },
        {
            "role": "user",
            "content": (
                f"Task: {prompt}\n"
                f"Target repository: {target_repo}\n"
                f"Branch: {branch}"
            ),
        },
    ]

    tool_results: list[str] = []
    files_written: list[str] = []

    for iteration in range(config.MAX_ITERATIONS):
        logger.info("Agent iteration %d/%d", iteration + 1, config.MAX_ITERATIONS)

        llm_reply = _call_llm(messages)
        logger.debug("LLM reply: %s", llm_reply)

        action = _parse_action(llm_reply)

        # Append the assistant turn so the LLM has conversation history
        messages.append({"role": "assistant", "content": llm_reply})

        if action.get("action") == "use_tool":
            tool_name = action.get("tool", "")
            params = action.get("params", {})
            logger.info("Executing tool: %s | params: %s", tool_name, params)

            try:
                result = tool_router.route(tool_name, params)
                result_str = json.dumps(result, ensure_ascii=False)
                tool_results.append(result_str)
                messages.append({"role": "user", "content": f"Tool result: {result_str}"})
            except Exception as exc:
                error_msg = f"Tool '{tool_name}' raised an error: {exc}"
                logger.error(error_msg)
                messages.append({"role": "user", "content": error_msg})

        elif action.get("action") == "write_file":
            file_path: str = action.get("path", "generated/output.txt")
            content: str = action.get("content", "")
            repo_manager.write_file(clone_path, file_path, content)
            files_written.append(file_path)
            logger.info("File written: %s", file_path)
            messages.append({"role": "user", "content": f"File '{file_path}' written successfully."})

        # Stop when the LLM signals completion
        if action.get("done", False):
            logger.info("Agent signalled completion after %d iteration(s).", iteration + 1)
            break

    if not files_written:
        logger.warning("Agent finished without writing any files.")
        return

    # Commit and push all generated files
    commit_message = f"feat: AI-generated changes\n\nPrompt: {prompt[:200]}"
    repo_manager.commit_and_push(clone_path, branch, message=commit_message)
    logger.info(
        "Done.  %d file(s) committed and pushed to %s/%s: %s",
        len(files_written),
        target_repo,
        branch,
        files_written,
    )


# ---------------------------------------------------------------------------
# CLI entry-point
# ---------------------------------------------------------------------------

def _parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="MCP AI Agent – executes a prompt using registered MCP tools."
    )
    parser.add_argument(
        "--prompt",
        required=True,
        help="The user's task description.",
    )
    parser.add_argument(
        "--target-repo",
        required=True,
        help="Target GitHub repository in owner/name format.",
    )
    parser.add_argument(
        "--branch",
        default="main",
        help="Branch in the target repository to push changes to.",
    )
    return parser.parse_args(argv)


if __name__ == "__main__":
    args = _parse_args()
    run_agent(
        prompt=args.prompt,
        target_repo=args.target_repo,
        branch=args.branch,
    )
